# fly.toml app configuration file generated for nlppp on 2023-08-01T11:30:33+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nlppp"
primary_region = "nrt"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_SECRET_KEY = "django-insecure--w297pf9z!be1kh3&+-$wdsqss##3_i2twg29^ebbt=f3*49*@"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[vm]
  size = "dedicated-cpu-4x"

[processes]
  web = "python manage.py runserver 0.0.0.0:$PORT"
